version: '2'
services:
    openvpn:
      env_file: ./docker.env
      cap_add:
        - NET_ADMIN
      image: kylemanna/openvpn
      container_name: openvpn
      ports:
        - "1194:1194/udp"
      restart: always
      volumes:
        - ${VPN_VOLUMEN_PATH:/opt/openvpn/data}:/etc/openvpn
